---
# tasks file for apps_role


- name: Include Debian-specific tasks
  ansible.builtin.import_tasks: tasks/Ubuntu.yml
  when: 
  - ansible_facts['os_family'] == "Debian"

- name: Include RedHat-specific tasks
  ansible.builtin.import_tasks: tasks/RedHat.yml
  when: 
  - ansible_facts['os_family'] == "RedHat"

- name: Include RedHat-specific tasks
  ansible.builtin.import_tasks: tasks/Windows.yml
  when: 
  - ansible_facts['os_family'] == "Windows"
