---
# tasks file for apps_role

- name: Gather the facts
  ansible.builtin.setup:

- name: Include Debian-specific tasks
  ansible.builtin.include_tasks: tasks/Ubuntu.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Include RedHat-specific tasks
  ansible.builtin.include_tasks: tasks/RedHat.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Include RedHat-specific tasks
  ansible.builtin.include_tasks: tasks/Windows.yml
  when: ansible_facts['os_family'] == "Windows"