---
# tasks file for apps_role Ubuntu

- name: Found Ubuntu version
  debug:
    msg: "Ubuntu version is '{{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}'"
- name: Update APT package index
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Tools list
  debug:
    var: app_packages

- name: Install net tools packages
  apt: 
    name: "{{ app_packages }}"
    state: latest
  become: true